### ISSUE TITLE
Fake Players

### ISSUE THREAD

**Issue by enterprise12nx** [KaiKikuchi/GriefPreventionPlus-Cities#12]
Hey i was wondering if it could be possible to allow fake players to work.

in GriefPrevention for 1.7.10 brackets arent allowed in the configs anymore so the section
"Players who ignore claims" does not really work anymore for fake players such as
[BuildCraft], [CoFH], etc.

Maybe its possible you could fix that for your plugin? it would be greatly appreciated to that fake players can be used in claims.

**Comment by KaiKikuchi** [comment]
Hello! This is not the correct plugin. Please reopen this here: https://github.com/KaiKikuchi/GriefPreventionPlus
