### ISSUE TITLE
can you fix siege mode

### ISSUE THREAD

**Issue by Flukethoughts** [KaiKikuchi/GriefPreventionPlus-Cities#14]
it seems to have issues can't pvp in claim while siege is going and on top of that i would like to make the winner of the siege able to loot chest and stuff for atleast five mins

**Comment by KaiKikuchi** [comment]
Hello, this is not related to GriefPreventionPlus-Cities.
Open this issue here: https://github.com/KaiKikuchi/GriefPreventionPlus
