### ISSUE TITLE
Database missing

### ISSUE THREAD

**Issue by Menphis88** [KaiKikuchi/GriefPreventionPlus-Cities#16]
I have successfully installes and used GPPlus for a week or 2 now, with a proper database.
But even still GPPlus-Cities, stays disabled and insists on not having a proper database to connect to.

GPPlus Config
http://pastebin.com/rYZNryP5

GPPlus-cities Config
http://pastebin.com/fRtLqiak

Server Log(only plugin loading part)
http://pastebin.com/ZmCidXAQ

**Comment by KaiKikuchi** [comment]
Database password on GPPlus config file can't be empty.
