### ISSUE TITLE
Can't expel

### ISSUE THREAD

**Issue by Flukethoughts** [KaiKikuchi/GriefPreventionPlus-Cities#17]
Can't expel offline users please fix thank you.
Can't expel in normal command or admin when the user is offline.

**Comment by KaiKikuchi** [comment]
Is there anything useful in your server log about this issue?

**Comment by KaiKikuchi** [comment]
This should be fixed in https://github.com/KaiKikuchi/GriefPreventionPlus-Cities/commit/3eac42c1579ca94c6c56426f3c842d7ee40999eb
