### ISSUE TITLE
Resizing claim when in a city, Negative claim blocks. 

### ISSUE THREAD

**Issue by axle2005** [KaiKikuchi/GriefPreventionPlus-Cities#19]
When resizing a claim that has been converted to a city claim, I can resize it indefinitely and it tells me I have negative claim blocks. 

http://imgur.com/a/r1cWL

**Comment by KaiKikuchi** [comment]
You can resize other players' claims if you're op. Normally, you can't resize other players' claims, and the message tells your count minus claim blocks used for resizing, even if it's not using your claim blocks. Anyway, not a GPPCities bug.
