### ISSUE TITLE
Admin Claims message still there

### ISSUE THREAD

**Issue by devryb** [KaiKikuchi/GriefPreventionPlus-Cities#2]
I have checked in the config that AdminClaimMessage: false
However whenever entering an administrative claim still you get "You're on someone's claim"

**Comment by KaiKikuchi** [comment]
It shouldn't be "someone's claim", but "an administrator's claim". This means there's a bug somewhere else... maybe in data migration. Can you PM me your original GP database, please?

**Comment by devryb** [comment]
Done

**Comment by KaiKikuchi** [comment]
This was a GPP's bug fixed here: https://github.com/KaiKikuchi/GriefPreventionPlus/commit/d7729b52f066c05fb2e3bdb6f8dbadbe0667f4ae
