### ISSUE TITLE
City admin commands

### ISSUE THREAD

**Issue by Kaelthanas** [KaiKikuchi/GriefPreventionPlus-Cities#20]
On our server AST 
Animated_jay made a city, and didn't invite me.
I tried to remove or make myself mayor and neither worked, 
also tried to join and it says invalid command

/ca Project_Alpha3 mayor Kaelthanas - can't be mayor when not part of a city
/ca Project_Alpha3 join - invalid command

Any ideas Kai?

**Comment by KaiKikuchi** [comment]
Fixed in 1.5.5. Thank you.
