### ISSUE TITLE
Cannot Create New City

### ISSUE THREAD

**Issue by Time6628** [KaiKikuchi/GriefPreventionPlus-Cities#21]
I cannot create a new city. 
When I try to create one, it makes it, then it can't make me a citizen of it, then it disbands it.
```
[GPPCities] Unable to create a new citizen for cattown
01.12 21:19:46 [Server] INFO [21:19:46 ERROR]: [GPPCities] Duplicate entry '\xC7\xD0D\xF4\x94\xDB@\xA0\x908\xAD\xD8G=>(' for key 'PRIMARY'
```
Is the error.
Latest GPPCities and GP+.

**Comment by KaiKikuchi** [comment]
Hello. Thank you for your report.

Please download GriefPreventionPlus 12.10 and GPPCities 1.6
