### ISSUE TITLE
Weird lag issue

### ISSUE THREAD

**Issue by devryb** [KaiKikuchi/GriefPreventionPlus-Cities#5]
Hey noticed this issue today looks like when a block is trying to burn it can cause some lag.
http://puu.sh/gr1iL/3ca2e0883f.png

**Comment by devryb** [comment]
Let me know if I should relog this under gpp instead, keep making tickets on cities when it probably should have been here..

**Comment by KaiKikuchi** [comment]
Yes, this is not GPP-Cities related at all. Actually it could be a GP bug, but let me handle it first.
