### ISSUE TITLE
Plot.isTakeable can return null values

### ISSUE THREAD

**Issue by PrestonTaylor** [KaiKikuchi/GriefPreventionPlus-Cities#6]
Null should not be a valid response here, this causes problems in some messages returned to players. Recommend using a getter (see below) and set the variable to private or at least setting defaults in all constructors.

Plot.getIsTakeable()
{
    if(isTakeable == null)
        return false;
    else 
        return isTakeable;
}

**Comment by KaiKikuchi** [comment]
Plot.isTakeable is a boolean primitive data type variable, and can't be null. True and false are the only accepted values. so "if(isTakeable == null)" is an invalid code.

http://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

If you get some weird messages, please let me know how to reproduce it.

**Comment by PrestonTaylor** [comment]
Sorry, this was incorrect. I was reading the returned message wrong. The "false" I was looking for is in the wrong spot. This is covered in another issue.
