### ISSUE TITLE
No admin tools

### ISSUE THREAD

**Issue by MCovey2011** [KaiKikuchi/GriefPreventionPlus-Cities#9]
Need admin commands to remove cities (i.e. inappropriate names, etc.). Also, I'm in my claim and it's my city but it's telling me I'm not a member and can't invite people.

**Comment by KaiKikuchi** [comment]
Hello! You can delete an inappropriate city with /c delete <CityName>
For the other issue, I'll check ingame! You typed /c new <CityName> while you're standing in your claim, right?

Please take a look at the wiki: https://github.com/KaiKikuchi/GriefPreventionPlus-Cities/wiki
